name: Sauvegarde d'un fichier sur le réseau IPFS
on: push
jobs:
  IPFS:
    name: Deploy IPFS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          jar cvf XavierMANTELLATO.war *
      - uses: jirutka/setup-alpine@v1
        with:
          branch: v3.15
      - run: |
          apk add go-ipfs
          ipfs init
          ipfs daemon &
        shell: alpine.sh --root {0}
      - name: Sauvegarde fichier war sur IPFS
        run: |
          ls -la 
          ipfs swarm peers
          ipfs add XavierMANTELLATO.war
        shell: alpine.sh --root {0}