name: Industrialisation continue sur le serveur AWS (Tomcat)
on: push
jobs:
  AWS:
    name: Deploy AWS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
          jar cvf XavierMANTELLATO.war *
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.DEPLOY_PORT }}
        source: "XavierMANTELLATO.war"
        target: "/opt/tomcat/webapps"

  IPFS:
    needs: AWS
    name: Deploy IPFS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          jar cvf XavierMANTELLATO.war *
      - uses: jirutka/setup-alpine@v1
        with:
          branch: v3.15
      - run: |
          apk add go-ipfs
          ipfs init
          ipfs daemon &
        shell: alpine.sh --root {0}
      - name: Sauvegarde fichier war sur IPFS
        run: |
          ls -la 
          ipfs swarm peers
          ipfs add XavierMANTELLATO.war > ipfsKey.txt
        shell: alpine.sh --root {0}

      name: Discord Notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: |
        ipfsKey=$(cat ipfsKey.txt)
        curl -X POST -H "Content-Type: application/json" -d "{"content": "Le workflow IPFS est terminé. Clé IPFS : $ipfsKey"}" $DISCORD_WEBHOOK